accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

cards/urls.py
from django.urls import path
from . import views

app_name = 'cards'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('<int:pk>/', views.DetailView.as_view(), name='card_detail'),
    path('create/', views.BoxCreateView.as_view(), name='box_create'),
    path('update/<int:pk>/', views.BoxUpdateView.as_view(), name='box_update'),
    path('delete/<int:pk>/', views.BoxDeleteView.as_view(), name='box_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cards.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

cards/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.conf import settings


class Box(models.Model):
    name = models.CharField(max_length=50, validators=[MinLengthValidator(3)])
    capacity = models.IntegerField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    state = models.IntegerField(choices=((0, "Public"), (1, "Private")), default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.name


class Card(models.Model):
    question = models.CharField(max_length=300,  validators=[MinLengthValidator(3)])
    answer = models.CharField(max_length=300, validators=[MinLengthValidator(3)])
    box = models.ForeignKey(Box, on_delete=models.CASCADE, null=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

cards/forms.py
from django import forms
from .models import Box

class BoxCreateForm(forms.ModelForm):

    class Meta:
        model = Box
        fields = ['name', 'capacity', 'state']

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

class SignUpView(CreateView):
    template_name = 'registration/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')

cards/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View

from .forms import BoxCreateForm
from .models import Card, Box
from .owner import OwnerDeleteView, OwnerListView
from django.urls import reverse_lazy

class MainView(OwnerListView):
    model = Box

class DetailView(LoginRequiredMixin, View):
    model = Card
    template_name = 'cards/card_detail.html'

    def get(self, request, pk):
        x = get_object_or_404(Card,box=pk)
        context = {'question': x.name, 'answer': x.answer}
        return render(request, self.template_name, context)


class BoxCreateView(LoginRequiredMixin, View):
    model = Box
    fields = ['name', 'capacity', 'state']
    template_name = 'cards/box_form.html'
    success_url = reverse_lazy('cards:all')

    def get(self, request):
        form = BoxCreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = BoxCreateForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        box = form.save(commit=False)
        box.owner = request.user
        box.save()
        return redirect(self.success_url)


class BoxUpdateView(LoginRequiredMixin, View):
    model = Box
    fields = ['name', 'capacity', 'state']
    template_name = 'cards/box_form.html'
    success_url = reverse_lazy('cards:all')

    def get(self, request, pk):
        box = get_object_or_404(Box, box=pk, owner=self.request.user)
        form = BoxCreateForm(instance=box)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        box = get_object_or_404(Box, box=pk, owner=self.request.user)
        form = BoxCreateForm(request.POST, instance=box)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        form.owner = request.user
        form.save()
        return redirect(self.success_url)


class BoxDeleteView(OwnerDeleteView):
    model = Box
    field = '__all__'
    success_url = reverse_lazy('cards:all')

cards/templates/cards/box_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        {% extends "base_bootstrap.html" %}

        {% block content %}

        <h1>Delete Auto</h1>

        <p>Are you sure you want to delete the card: {{ card }}?</p>

        <form action="" method="POST">
          {% csrf_token %}
          <input type="submit" value="Yes, delete.">
        </form>

        {% endblock %}</body>
</html>

cards/templates/cards/box_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends 'base_bootstrap.html' %}
    {% block content %}
    <p>
        <form action="" method="post" id="upload_form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
        <input type="submit" value="Reset">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'cards:all' %}'; return false;">
        </form>
    </p>
    {% endblock %}
</body>
</html>

cards/templates/cards/box_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    {% extends "base_bootstrap.html" %}

    {% block content %}
    <a href="{% url 'cards:box_create' %}"><h2> Create New Box</h2></a>
        <h2>
            All boxes
        </h2>
        {% for box in box_list %}
            <h3>🗃 {{ box.name }} Box
            <a href=" {% url 'cards:box_update' pk=box.pk %} ">
                Update!
            </a>
            <a href=" {% url 'cards:box_delete' pk=box.pk %} ">
                Delete!
            </a>
            </h3>
            <a href=" {% url 'cards:card_detail' pk=box.pk %} ">
                See Inside
            </a>
        {% endfor %}
    {% endblock content %}
</body>
</html>

cards/templates/cards/card_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        {% extends "base_bootstrap.html" %}

        {% block content %}

        <h1>Delete Auto</h1>

        <p>Are you sure you want to delete the card: {{ card }}?</p>

        <form action="" method="POST">
          {% csrf_token %}
          <input type="submit" value="Yes, delete.">
        </form>

        {% endblock %}</body>
</html>

cards/templates/cards/card_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base_bootstrap.html" %}

    {% block content %}
        <h1>
        {{ question }}
        </h1>
        <h2>
        {{ answer }}
        </h2>
    {% endblock content %}
</body>
</html>

cards/templates/cards/card_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends 'base_bootstrap.html' %}
    {% block content %}
    <p>
        <form action="" method="post" id="upload_form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
        <input type="submit" value="Reset">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'cards:all' %}'; return false;">
        </form>
    </p>
    {% endblock %}
</body>
</html>

cards/templates/cards/card_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    {% extends "base_bootstrap.html" %}

    {% block content %}
    <a href="{% url 'cards:create' %}"><h2> Create New Card</h2></a>
        <h2>
            All Cards
        </h2>
        {% for card in card_list %}
            <h3>🗃 {{ card.box }} Box</h3>
            <a href="{% url 'cards:detail' pk=card.id %}">
            <article>
                {{ card }}
            </article>
            </a>
            <a href=" {% url 'cards:update' pk=card.pk %} ">
                Update!
            </a>
            <a href=" {% url 'cards:delete' pk=card.pk %} ">
                Delete!
            </a>
        {% endfor %}
    {% endblock content %}
</body>
</html>

cards/templates/cards/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    {% extends "base_bootstrap.html" %}

    {% block content %}
        <h2>
            All Cards
        </h2>
        {% for card in card_list %}
            <h3>🗃 {{ card.box }} Box</h3>
            <article>
                {{ card }}
            </article>
        {% endfor %}
    {% endblock content %}
</body>
</html>

templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>

<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="d9ed13c2f3ef63f67ba950b489c4052c">

<meta name="dj4e-code" content="42176715165354">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2026-01-01">

{% block head %} {% endblock %}

</head>
<body>
{% block navbar %} {% endblock %}
<div class="container">
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

templates/base_menu.html
{% extends 'base_bootstrap.html' %}
{% load app_tags %} <!-- see home/templatetags/app_tags.py and dj4e-samples/settings.py -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mkt:all' %}">{{ settings.APP_NAME }}</a>
    <ul class="navbar-nav">
      {% url 'mkt:all' as x %}
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'mkt:all' %}" role="button">Ads</a></li>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li>
         <a class="nav-link" href="{% url 'mkt:ad_create' %}">Create Ad</a>
      </li>
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
            <li>
                <form action="{% url 'logout' %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{% url 'mkt:all' %}">
                    <button class="dropdown-item btn btn-link" type="submit">Logout</button>
                </form>
            </li>
        </ul>
       </li>
       {% else %}
       <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={% url 'mkt:all' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}